version: '3'

services:
  postgres-container:
    image: postgres
    container_name: postgres-mentesa
    environment:
      POSTGRES_PASSWORD: '12345'
    ports:
      - '15432:5432'
    volumes:
      - gama-academy:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin4-container:
    image: dpage/pgadmin4
    container_name: pgadmin4-mentesa
    environment:
      PGADMIN_DEFAULT_EMAIL: 'mentesa@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '12345'
    ports:
      - '16543:80'
    depends_on:
      - postgres-container
    networks:
      - postgres-compose-network

volumes:
  gama-academy:
    external: false

networks:
  postgres-compose-network:
    driver: bridge
